name: Notes

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm install
      run: npm install

    - name: npm build
      run: npm run build

    - uses: docker://docker:latest

    - name: Checking docker version
      run: docker build -t greenfrogab/notes-nodejs:latest .

    - name: Login to Docker Hub
      run: docker login -u ${{secrets.DOCKER_HUB_USERNAME}} -p ${{secrets.DOCKER_HUB_PASSWORD}}

    - name: Push image to docker hub
      run: docker push greenfrogab/notes-nodejs:latest

    - name: Logout from Docker Hub
      run: docker logout


      env:
        CI: true
